[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = false     #allows foundry to run commands directly on your machine, should be off 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
